import { avatarMarkup } from './images.js';
const esc=value=>String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arrow='<svg class="mc-row-arrow" viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 7 7-7 7"/></svg>';
const row=(label,value,action,attrs='')=>`<button type="button" class="mc-nav-row" data-action="${action}" ${attrs}><span>${esc(label)}</span><span class="mc-row-value">${esc(value)}</span>${arrow}</button>`;
const avatar=(name,image='')=>avatarMarkup(name,image);
export const CONTACT_FIELDS={name:'角色姓名',userName:'我的称呼',personaMode:'人设来源',description:'角色人设',supplements:'补充设定',personality:'性格',scenario:'场景与背景',speech:'说话习惯与示例',relationship:'双方关系',userPersona:'我的人设',world:'补充世界设定',notes:'补充说明'};
export function contactTitle(ui) {
    if(ui.contactPage==='picker')return {cards:'选择角色卡',book:'选择世界书',entries:'选择条目',supplements:'补充世界书',supplementEntries:'选择补充条目'}[ui.pickerKind] || '选择来源';
    return {list:'联系人',detail:'联系人详情',add:'添加联系人',candidates:'选择人物',supplements:'补充设定',field:CONTACT_FIELDS[ui.contactField]}[ui.contactPage] || '联系人';
}
export function contactsScreen(state,ui,context,busy) {
    const page=ui.contactPage || 'list',person=state.profiles.find(p=>p.id===ui.editorId),disabled=busy?'disabled':'',source=ui.sourceDraft;
    const wrap=content=>`<div class="mc-scroll mc-contacts" data-contact-page="${page}">${content}</div>`;
    if(page==='list')return wrap(`<label class="mc-contact-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></svg><input name="contactSearch" placeholder="搜索联系人" aria-label="搜索联系人"></label><div class="mc-contact-heading"><span>联系人</span><button type="button" data-action="contact-add" ${disabled}>＋ 添加</button></div><div class="mc-row-group">${state.profiles.map(p=>`<button type="button" class="mc-person-row" data-action="contact-open" data-id="${esc(p.id)}" data-contact-name="${esc(p.name.toLowerCase())}">${avatar(p.name,p.avatarImage)}<strong>${esc(p.name)}</strong>${arrow}</button>`).join('') || '<p class="mc-contact-empty">还没有联系人</p>'}</div>`);
    if(page==='detail' && person)return wrap(`<div class="mc-contact-identity">${avatarMarkup(person.name,person.avatarImage,'avatar-settings',`data-target="contact" data-id="${esc(person.id)}" aria-label="更换联系人头像"`)}<strong>${esc(person.name)}</strong></div><div class="mc-row-group">${row('角色头像',person.avatarImage?'自定义':'默认','avatar-settings',`data-target="contact" data-id="${esc(person.id)}"`)}${row('我的头像',state.social.avatar?'自定义':'默认','avatar-settings','data-target="user"')}${row('角色姓名',person.name,'contact-field','data-field="name"')}${row('我的称呼',person.userName || context.name1,'contact-field','data-field="userName"')}${row('人设来源',person.personaMode==='inherit'?(person.binding?.avatar?'沿用角色卡':'沿用世界书条目'):'独立人设','contact-field','data-field="personaMode"')}${row('角色人设','','contact-field','data-field="description"')}${ui.contactReturn==='chat'?row('发送内容预览','','preview',`data-id="${esc(person.id)}"`):''}${row('补充设定',person.supplementalBooks.length?`${person.supplementalBooks.length} 本世界书`:'未选择','contact-supplements')}</div><button type="button" class="mc-primary mc-contact-primary" data-action="contact-chat" data-id="${esc(person.id)}">发消息</button><button type="button" class="mc-contact-delete" data-action="delete-profile" ${disabled}>删除联系人</button>`);
    if(page==='field' && person) {
        const key=ui.contactField,label=CONTACT_FIELDS[key],readOnly=person.personaMode==='inherit' && ['description','personality','scenario','speech'].includes(key);
        let field=key==='personaMode'?`<label class="mc-field"><span>${label}</span><select name="personaMode"><option value="inherit" ${person.personaMode==='inherit'?'selected':''} ${person.binding?'':'disabled'}>沿用${person.binding?.avatar?'角色卡人设':'世界书条目'}</option><option value="manual" ${person.personaMode!=='inherit'?'selected':''}>独立人设</option></select></label>`:['name','userName'].includes(key)?`<label class="mc-field"><span>${label}</span><input name="${key}" value="${esc(person[key])}"></label>`:`<label class="mc-field"><span>${label}</span><textarea name="${key}" rows="12" ${readOnly?'readonly':''}>${esc(person[key])}</textarea></label>`;
        if(readOnly)field+='<p class="mc-muted">当前沿用原始设定。需要编辑时，可在人设来源中切换为独立人设。</p>';
        if(key==='description')field+=`<div class="mc-row-group">${['personality','scenario','speech','relationship','userPersona'].map(k=>row(CONTACT_FIELDS[k],'','contact-field',`data-field="${k}"`)).join('')}</div>`;
        return wrap(field+`<button type="button" class="mc-primary mc-contact-primary" data-action="save-profile" ${disabled}>保存</button>`);
    }
    if(page==='supplements' && person)return wrap(`<div class="mc-row-group">${row('补充世界书',ui.supplementDraft.length?`已选 ${ui.supplementDraft.length} 本`:'选择世界书','contact-picker','data-kind="supplements"')}</div>${ui.supplementDraft.length?`<div class="mc-row-group">${ui.supplementDraft.map((b,i)=>row(b.name,b.ids===null?'全部启用条目':`${b.ids.length} 个条目`,'contact-picker',`data-kind="supplementEntries" data-index="${i}"`)).join('')}</div>`:''}<p class="mc-muted">只读取这里选中的世界书。可继续点入指定条目。</p><div class="mc-row-group">${row('补充世界设定','','contact-field','data-field="world"')}${row('补充说明','','contact-field','data-field="notes"')}</div><button type="button" class="mc-primary mc-contact-primary" data-action="save-supplements" ${disabled}>保存补充设定</button>`);
    if(page==='add')return wrap(`<div class="mc-contact-segments">${[['card','角色卡'],['book','世界书'],['manual','手动']].map(([value,label])=>`<button type="button" data-action="contact-source" data-value="${value}" class="${ui.contactSource===value?'mc-active':''}" ${disabled}>${label}</button>`).join('')}</div><div class="mc-row-group">${ui.contactSource==='card'?row('角色卡',source.cards?.length?`已选 ${source.cards.length} 张`:'选择角色卡','contact-picker','data-kind="cards"'):row('世界书',source.personaBook || '选择世界书','contact-picker','data-kind="book"')+row('条目',source.personaEntries?.length?`已选 ${source.personaEntries.length} 项`:'选择条目','contact-picker','data-kind="entries"')}</div>${ui.contactSource==='book'?'<p class="mc-muted">选择条目后，自动识别其中的人物。</p>':'<p class="mc-muted">直接沿用角色卡人设。补充世界书可在联系人详情中选择。</p>'}<button type="button" class="mc-primary mc-contact-primary" data-action="contact-identify" ${disabled}>${ui.contactSource==='card'?'选择联系人':'重新识别人物'}</button>`);
    if(page==='candidates')return wrap(`<div class="mc-contact-heading"><span>已识别 ${ui.contactCandidates.length} 位</span><button type="button" data-action="contact-all" ${disabled}>全选</button></div><div class="mc-row-group">${ui.contactCandidates.map((p,i)=>`<button type="button" class="mc-person-row" data-action="contact-candidate" data-index="${i}" aria-pressed="${ui.candidateSelection.includes(i)}" ${disabled}>${avatar(p.name,p.avatarImage)}<strong>${esc(p.name)}</strong><span class="mc-selection ${ui.candidateSelection.includes(i)?'mc-checked':''}">${ui.candidateSelection.includes(i)?'✓':''}</span></button>`).join('')}</div><button type="button" class="mc-primary mc-contact-primary" data-action="contact-create" ${!ui.candidateSelection.length || busy?'disabled':''}>添加 ${ui.candidateSelection.length} 位联系人</button>`);
    if(page==='picker') {
        let options=[],selected=[];const kind=ui.pickerKind;
        if(kind==='cards'){options=(context.characters || []).map((c,i)=>({id:String(i),name:c.name || c.data?.name || '未命名'}));selected=ui.pickerSelection;}
        if(kind==='book' || kind==='supplements'){options=(context.getWorldInfoNames?.() || []).map(name=>({id:name,name}));selected=ui.pickerSelection;}
        if(kind==='entries' || kind==='supplementEntries'){options=ui.pickerEntries.map(e=>({id:e.id,name:e.name+(e.disabled?'（已关闭）':''),disabled:kind==='supplementEntries' && e.disabled}));selected=ui.pickerSelection;}
        return wrap(`<div class="mc-contact-heading"><span>${kind==='book'?'选择一本世界书':'可多选'}</span>${kind==='book'?'':`<button type="button" data-action="contact-picker-all" ${disabled}>全选</button>`}</div><div class="mc-row-group">${options.map(o=>`<button type="button" class="mc-nav-row" data-action="contact-picker-toggle" data-id="${esc(o.id)}" aria-pressed="${selected.includes(o.id)}" ${busy || o.disabled?'disabled':''}><span>${esc(o.name)}</span><span class="mc-selection ${selected.includes(o.id)?'mc-checked':''}">${selected.includes(o.id)?'✓':''}</span></button>`).join('') || '<p class="mc-contact-empty">没有可选项目</p>'}</div><button type="button" class="mc-primary mc-contact-primary" data-action="contact-picker-done" ${disabled}>确定${selected.length?`（${selected.length}）`:''}</button>`);
    }
    return wrap('<p class="mc-contact-empty">请返回联系人列表</p>');
}
