export const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={chat:'<path d="M4 5h16v12H9l-5 4V5Z"/><path d="M8 11h.01M12 11h.01M16 11h.01"/>',story:'<circle cx="9" cy="12" r="7"/><circle cx="15" cy="12" r="7"/>',company:'<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>',roles:'<circle cx="12" cy="7" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3H4Z"/>',moments:'<circle cx="12" cy="12" r="9"/><path d="m12 3 5 9-10 0 5-9ZM21 12l-10 6 0-12 10 6ZM12 21 7 12h10l-5 9Z"/>',diary:'<path d="M5 3h12v18H5V3ZM3 7h4M3 12h4M3 17h4M9 7h5M9 11h5M9 15h3M19 4l3 1-4 13-3 2 1-4 3-12Z"/>',settings:'<path d="m9 3-1 3-3 1-2 4 2 2v4l4 2 3-1 3 1 4-2v-4l2-2-2-4-3-1-1-3H9Z"/><circle cx="12" cy="12" r="3"/>'};
export const icon = key => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[key] || paths.chat}</svg>`;
export const APPS=[['chat','消息'],['story','共看'],['company','陪伴'],['roles','联系人'],['moments','朋友圈'],['diary','日记'],['settings','设置']];
export function homeScreen() {return `<div class="mc-scroll mc-home"><div class="mc-home-time"><time id="mc-home-time"></time><span id="mc-home-date"></span></div><nav class="mc-app-grid" aria-label="手机应用">${APPS.map(([key,label])=>`<button type="button" data-action="tab" data-tab="${key}" class="mc-app"><span class="mc-app-tile">${icon(key)}</span><span>${label}</span></button>`).join('')}</nav><div class="mc-page-dots" aria-hidden="true"><b></b></div></div>`;}
const when = value => new Date(value).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
const avatar = (name,image='',action='') => `<${action?'button':'span'} ${action?`type="button" data-action="${action}"`:''} class="mc-social-avatar" ${action?'aria-label="设置我的状态和朋友圈角色"':''}>${image?`<img src="${esc(image)}" alt="头像">`:esc(name?.slice(0,1) || '我')}</${action?'button':'span'}>`;
const roleChecks=(state,name,selected)=>`<div class="mc-role-checks">${state.profiles.map(p=>`<label><input type="checkbox" name="${name}:${esc(p.id)}" ${selected.includes(p.id)?'checked':''}><span>${esc(p.name)}</span></label>`).join('') || '<p class="mc-muted">先在联系人中添加角色</p>'}</div>`;
const num=(label,name,value,min,max)=>`<label class="mc-field"><span>${label}</span><input type="number" name="${name}" value="${value}" min="${min}" max="${max}"></label>`;
const pending=()=>'<span class="mc-pending">角色生成 · 待接入提示词</span>';
function settings(state,kind) {
    const s=state.social.settings;return `${roleChecks(state,kind+'Roles',s[kind+'Roles'])}<label class="mc-check"><input type="checkbox" name="${kind}Auto" ${s[kind+'Auto']?'checked':''}>按现实时间自动生成</label><div class="mc-two">${num('生成间隔（分钟）',kind+'Minutes',s[kind+'Minutes'],1,10080)}${num('每个角色每日生成上限',kind+'Daily',s[kind+'Daily'],1,100)}</div>${pending()}<p class="mc-muted">每日上限包含手动与自动生成。酒馆保持运行且回到前台时检查，关闭小手机也能运行；错过的间隔不会补发多篇。</p>`;
}
function comments(entry) {return entry.comments.length?`<div class="mc-social-comments">${entry.comments.map(c=>`<div><strong>${esc(c.authorName || '我')}：</strong><span>${esc(c.text)}</span></div>`).join('')}</div>`:'';}
function commentEditor(entry,state) {
    const kind=entry.kind;const ids=state.social.settings[kind==='moment'?'momentCommentRoles':'diaryCommentRoles'];
    return `<div class="mc-inline-comment"><label class="mc-field"><span>你的评论</span><textarea name="comment:${esc(entry.id)}" rows="2" placeholder="写下评论…"></textarea></label><button type="button" data-action="social-comment" data-kind="${kind}" data-id="${esc(entry.id)}">发布评论</button><label class="mc-field"><span>请角色评论</span><select name="commentRole"><option value="">选择角色</option>${state.profiles.filter(p=>ids.includes(p.id)).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></label><button type="button" data-action="social-generate-comment" data-kind="${kind}" data-id="${esc(entry.id)}">生成角色评论</button>${pending()}</div>`;
}
export function momentsScreen(state,ui,userName,busy) {
    const social=state.social;const name=social.userName || userName || '我';const disabled=busy?'disabled':'';
    let sheet='';
    if(ui.socialSheet==='moment-compose')sheet=`<section class="mc-social-sheet"><div class="mc-sheet-heading"><strong>发表朋友圈</strong><button data-action="social-dismiss" type="button">取消</button></div><textarea name="momentText" rows="4" maxlength="20000" placeholder="这一刻的想法…"></textarea><div class="mc-photo-preview">${ui.momentPhotos.map(src=>`<img src="${esc(src)}" alt="待发布图片">`).join('')}</div><div class="mc-toolbar"><button type="button" data-action="moment-photos">本地选图</button><button type="button" data-action="moment-clear-photos">清空图片</button><button type="button" class="mc-primary" data-action="moment-publish" ${disabled}>发表</button></div></section>`;
    if(ui.socialSheet==='moment-settings')sheet=`<section class="mc-social-sheet"><div class="mc-sheet-heading"><strong>我的朋友圈</strong><button type="button" data-action="social-dismiss">完成</button></div><label class="mc-field"><span>我的名字</span><input name="socialUserName" value="${esc(name)}" maxlength="160"></label><label class="mc-field"><span>微信状态</span><input name="socialStatus" value="${esc(social.status)}" maxlength="80" placeholder="摸鱼 / 忙碌 / 发呆…"></label><div class="mc-status-presets">${['在线','忙碌','摸鱼','发呆','睡觉'].map(s=>`<button type="button" data-action="social-status" data-value="${s}">${s}</button>`).join('')}</div><div class="mc-toolbar"><button type="button" data-action="social-avatar">更换头像</button><button type="button" data-action="moment-cover">更换背景</button><button type="button" data-action="moment-reset-cover">恢复背景</button></div><h3>可发朋友圈的角色</h3>${settings(state,'moment')}<h3>可评论朋友圈的角色</h3>${roleChecks(state,'momentCommentRoles',social.settings.momentCommentRoles)}<button type="button" class="mc-primary" data-action="save-moment-settings" ${disabled}>保存</button></section>`;
    if(ui.socialSheet==='generate-moment')sheet=generationSheet(state,ui,'moment',busy);
    const feed=social.moments.slice().reverse().map(entry=>`<article class="mc-feed-post">${avatar(entry.authorName,entry.authorType==='user'?social.avatar:'')}<div class="mc-feed-body"><strong class="mc-author">${esc(entry.authorType==='user'?name:entry.authorName)}</strong><div class="mc-social-text">${esc(entry.text)}</div>${entry.images.length?`<div class="mc-post-photos ${entry.images.length===1?'mc-single-photo':''}">${entry.images.map(src=>`<button type="button" data-action="social-view-photo" data-id="${esc(entry.id)}" data-index="${entry.images.indexOf(src)}"><img src="${esc(src)}" alt="朋友圈图片" loading="lazy"></button>`).join('')}</div>`:''}<div class="mc-post-actions"><small>${when(entry.createdAt)}</small>${entry.authorType==='user'?`<button type="button" data-action="social-delete" data-kind="moment" data-id="${esc(entry.id)}">删除</button>`:''}<button type="button" data-action="moment-like" data-id="${esc(entry.id)}" aria-label="${entry.liked?'取消点赞':'点赞'}">${entry.liked?'♥':'♡'}</button><button type="button" data-action="social-comment-open" data-kind="moment" data-id="${esc(entry.id)}" aria-label="评论">••</button></div>${entry.liked?'<div class="mc-likes">♡ 你</div>':''}${comments(entry)}${ui.commentTarget===entry.id?commentEditor({...entry,kind:'moment'},state):''}</div></article>`).join('');
    return `<div class="mc-scroll mc-moments"><div class="mc-moments-cover">${social.cover?`<img class="mc-cover-image" src="${esc(social.cover)}" alt="朋友圈背景">`:''}<button type="button" class="mc-cover-change" data-action="moment-cover">换背景</button><div class="mc-moments-identity"><div><strong>${esc(name)}</strong>${social.status?`<span>${esc(social.status)}</span>`:''}</div>${avatar(name,social.avatar,'moment-settings')}</div></div><div class="mc-moment-tools"><button type="button" data-action="moment-compose">＋ 发朋友圈</button><button type="button" data-action="social-generate" data-kind="moment" ${disabled}>角色发动态</button></div>${sheet}${feed || '<div class="mc-empty"><strong>分享这一刻</strong><p>你和角色的日常，会留在这里。</p></div>'}</div>`;
}
export function diaryScreen(state,ui,busy) {
    const social=state.social;const disabled=busy?'disabled':'';const name=social.userName || ui.host.context().name1 || '我';
    let sheet='';
    if(ui.socialSheet==='diary-compose')sheet=`<section class="mc-social-sheet"><div class="mc-sheet-heading"><strong>写我的日记</strong><button type="button" data-action="social-dismiss">取消</button></div><input name="diaryTitle" placeholder="标题（可选）" maxlength="160"><textarea name="diaryText" rows="7" maxlength="20000" placeholder="今天想记住什么？"></textarea><button type="button" class="mc-primary" data-action="diary-publish" ${disabled}>保存日记</button></section>`;
    if(ui.socialSheet==='diary-settings')sheet=`<section class="mc-social-sheet"><div class="mc-sheet-heading"><strong>日记本设置</strong><button type="button" data-action="social-dismiss">完成</button></div><h3>可生成日记的角色</h3>${settings(state,'diary')}<h3>可评论日记本的角色</h3>${roleChecks(state,'diaryCommentRoles',social.settings.diaryCommentRoles)}<button type="button" class="mc-primary" data-action="save-diary-settings" ${disabled}>保存</button></section>`;
    if(ui.socialSheet==='generate-diary')sheet=generationSheet(state,ui,'diary',busy);
    const entries=social.diaries.filter(x=>x.authorType===(ui.diaryTab==='user'?'user':'character')).slice().reverse();
    return `<div class="mc-scroll mc-diary"><div class="mc-diary-tabs"><button type="button" data-action="diary-tab" data-value="character" class="${ui.diaryTab==='character'?'mc-selected':''}">角色日记</button><button type="button" data-action="diary-tab" data-value="user" class="${ui.diaryTab==='user'?'mc-selected':''}">我的日记</button></div><div class="mc-toolbar"><button type="button" class="mc-primary" data-action="${ui.diaryTab==='user'?'diary-compose':'social-generate'}" data-kind="diary" ${disabled}>${ui.diaryTab==='user'?'＋ 写日记':'生成角色日记'}</button><button type="button" data-action="diary-settings">日记本设置</button></div>${sheet}${entries.map(entry=>`<article class="mc-diary-entry"><header><span>${esc(entry.authorType==='user'?name:entry.authorName)}</span><small>${when(entry.createdAt)}</small></header>${entry.title?`<h3>${esc(entry.title)}</h3>`:''}<div class="mc-social-text">${esc(entry.text)}</div><div class="mc-post-actions"><button type="button" data-action="social-comment-open" data-kind="diary" data-id="${esc(entry.id)}">评论 ${entry.comments.length || ''}</button>${entry.authorType==='user'?`<button type="button" data-action="social-delete" data-kind="diary" data-id="${esc(entry.id)}">删除</button>`:''}</div>${comments(entry)}${ui.commentTarget===entry.id?commentEditor({...entry,kind:'diary'},state):''}</article>`).join('') || '<div class="mc-empty"><strong>日记本还是空的</strong><p>把日常留在这一页。</p></div>'}</div>`;
}

export function generationSheet(state,ui,kind,busy) {
    const allowed=state.social.settings[kind+'Roles'];
    return `<section class="mc-social-sheet"><div class="mc-sheet-heading"><strong>${kind==='moment'?'角色发动态':'生成角色日记'}</strong><button type="button" data-action="social-dismiss">取消</button></div><label class="mc-field"><span>选择角色</span><select name="generateRole"><option value="">请选择</option>${state.profiles.filter(p=>allowed.includes(p.id)).map(p=>`<option value="${esc(p.id)}" ${p.id===state.selected?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label>${pending()}<button type="button" class="mc-primary" data-action="social-generate-confirm" data-kind="${kind}" ${busy?'disabled':''}>生成</button><p class="mc-muted">先在${kind==='moment'?'我的头像':'日记本设置'}中允许角色生成。</p></section>`;
}
