import { createRequire } from 'node:module';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
const require=createRequire(import.meta.url);
const dependency=require.resolve('happy-dom',{paths:[process.env.META_TEST_NODE_MODULES || '',path.resolve(import.meta.dirname,'..')]});
const { Window }=await import(pathToFileURL(dependency).href);
const base=path.resolve(import.meta.dirname,'..');
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const window=new Window({url:'http://localhost/tests/fixture.html',width:390,height:844});
const document=window.document;
for(const key of ['window','document','localStorage','navigator','HTMLElement','Element']) Object.defineProperty(globalThis,key,{value:window[key]||window,configurable:true});
globalThis.confirm=()=>true;
const html=await readFile(path.join(base,'tests/fixture.html'),'utf8');
document.write(html);window.eval(document.querySelector('script:not([type])').textContent);
globalThis.SillyTavern=window.SillyTavern;globalThis.STBaiBaiBook=window.STBaiBaiBook;
Object.defineProperty(document,'visibilityState',{value:'visible',configurable:true});
const errors=[];const oldError=console.error;console.error=(...args)=>{errors.push(String(args[1]?.message||args[0]));};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(fn,label){for(let i=0;i<300;i++){if(fn())return;await sleep(5);}throw Error('Timed out: '+label);}
const $=s=>document.querySelector(s);const click=s=>{if(s.startsWith('[data-tab=') && !$(s))$('[data-action="tab"][data-tab="home"]').click();assert.ok($(s),'missing '+s);$(s).click();};
const fill=(name,value)=>{assert.ok($(`[name="${name}"]`),name);$(`[name="${name}"]`).value=value;};
const switchRole=name=>{const select=$('#mc-profile');select.value=[...select.options].find(o=>o.textContent===name).value;select.dispatchEvent(new window.Event('change'));};
try {
 await import(pathToFileURL(path.join(base,'index.js')).href);document.dispatchEvent(new window.Event('DOMContentLoaded'));
 await wait(()=>$('#mc-wand-button'),'initialization');assert.equal($('#mc-launcher'),null);click('#mc-wand-button');
 await wait(()=>$('#mc-profile').options.length===2 && !$('#mc-status').textContent.includes('正在输入'),'automatic extraction');click('[data-tab="roles"]');
 await wait(()=>$('#mc-profile').options.length===2,'multi character extraction');assert.equal($('[name="name"]').value,'Alpha');
 assert.match(window.mockRequests[0].prompt[0].content,/城市背景/);
 globalThis.quickReplyApi=window.quickReplyApi;window.mockEmit('APP_READY');await wait(()=>window.qrCalls.includes('/meta'),'delayed QR import');assert.deepEqual([...window.qrCalls],['set','/meta','enable']);assert.equal(window.quickReplyApi.settings.isEnabled,true);assert.ok(window.qrSaves>1,'QR must persist after setting command text');window.mockEmit('APP_READY');await sleep(10);assert.equal(window.qrCalls.length,3);
 const extractions=()=>window.mockRequests.filter(r=>r.systemPrompt.includes('人物设定整理器')).length;
 click('[data-action="close"][aria-label]');click('#mc-wand-button');await sleep(350);assert.equal(extractions(),1,'unchanged card must reuse extraction');
 fill('personality','我自己修改的人设');click('[data-action="save-profile"]');await wait(()=>$('#mc-notice').textContent.includes('角色资料已保存'),'manual edits');
 window.mockContext.characters[0].description+='新的设定';window.mockEmit('WORLDINFO_UPDATED');await wait(()=>extractions()===2 && !$('#mc-status').textContent.includes('正在输入'),'source refresh');assert.equal($('[name="personality"]').value,'我自己修改的人设');assert.equal($('#mc-profile').options.length,2);

 click('[data-tab="chat"]');fill('draft','切日记也要保留的消息草稿');click('[data-tab="diary"]');click('[data-action="diary-tab"][data-value="user"]');click('[data-tab="chat"]');assert.equal($('#mc-draft').value,'切日记也要保留的消息草稿');
 fill('draft','我的第一条');window.mockDelay=100;click('[data-action="send"]');switchRole('Beta');
 await wait(()=>!$('#mc-status').textContent.includes('正在输入'),'role-switch generation');assert.ok(!$('.mc-messages').textContent.includes('我的第一条'));
 switchRole('Alpha');assert.ok($('.mc-messages').textContent.includes('我的第一条'));assert.ok($('.mc-messages').textContent.includes('Alpha：收到'));
 window.mockDelay=0;click('[data-tab="story"]');assert.equal($('[name="cutoff"]'),null);
 await wait(()=>$('[name="regexIds"] option'),'enabled regex list');fill('includeTags','正文');fill('excludeTags','状态栏');click('[data-action="save-story-settings"]');await wait(()=>$('#mc-notice').textContent.includes('读取设置已保存'),'story settings');
 window.mockContext.chat.push({name:'Alpha',is_user:false,mes:'<正文>新的自动同步剧情</正文><状态栏>秘密状态</状态栏>'});window.mockEmit('MESSAGE_RECEIVED');
 await wait(()=>$('#mc-content').textContent.includes('新的自动同步剧情'),'automatic main sync');assert.ok(!$('#mc-content').textContent.includes('秘密状态'));
 window.mockContext.chat.at(-1).mes='<正文>修改后的剧情</正文>';window.mockEmit('MESSAGE_EDITED');await wait(()=>$('#mc-content').textContent.includes('修改后的剧情'),'edited main sync');
 click('[data-action="annotate"]');await wait(()=>!$('#mc-status').textContent.includes('正在输入'),'annotation');assert.ok($('#mc-content').textContent.includes('你们留下的批注'));
 fill('includeTags','');const regexSelect=$('[name="regexIds"]');regexSelect.options[0].selected=true;click('[data-action="save-story-settings"]');await wait(()=>$('#mc-notice').textContent.includes('读取设置已保存'),'regex extraction settings');
 fill('memoryBook','测试世界');$('[name="memoryBook"]').dispatchEvent(new window.Event('change',{bubbles:true}));await wait(()=>$('[name="memoryEntry"] option[value="0"]'),'memory entries');fill('memoryEntry','0');fill('storyMemorySource','worldbook');click('[data-action="save-story-settings"]');await wait(()=>$('#mc-notice').textContent.includes('读取设置已保存'),'worldbook memory');
 click('[data-tab="chat"]');fill('draft','现在看到哪了');click('[data-action="send"]');await wait(()=>!$('#mc-status').textContent.includes('正在输入'),'latest story send');assert.match(window.mockRequests.at(-1).systemPrompt,/修改后的剧情|城市背景/);assert.ok(!window.mockRequests.at(-1).systemPrompt.includes('摘要截至'));
 window.failOnce=true;fill('draft','重试的消息');click('[data-action="send"]');await wait(()=>$('#mc-notice').textContent.includes('模拟网络失败'),'API error');click('[data-action="retry"]');await wait(()=>!$('#mc-status').textContent.includes('正在输入'),'retry');assert.equal([...document.querySelectorAll('.mc-user')].filter(n=>n.textContent.includes('重试的消息')).length,1);
 click('[data-tab="company"]');fill('activity','一起写东西');click('[data-action="start-company"]');await wait(()=>$('#mc-notice').textContent.includes('已开始'),'company start');click('[data-action="nudge"]');await wait(()=>!$('#mc-status').textContent.includes('正在输入'),'nudge');click('[data-tab="chat"]');assert.ok($('.mc-messages').textContent.includes('主动消息'));
 click('[data-tab="company"]');click('[data-action="stop-company"]');await wait(()=>$('#mc-notice').textContent.includes('已结束'),'company stop');fill('scene','便利店停电了');click('[data-action="theatre"]');await wait(()=>!$('#mc-status').textContent.includes('正在输入'),'theatre');assert.ok($('.mc-messages').textContent.includes('便利店停电了'));
 click('[data-tab="settings"]');fill('customInstruction','自然一点');click('[data-action="save-settings"]');await wait(()=>$('#mc-notice').textContent.includes('已保存'),'settings');
 const readState=()=>JSON.parse(localStorage.getItem('meta-companion:state:'+localStorage.getItem('meta-companion:scope')));
 $('[name="autoSummary"]').checked=true;fill('summaryEvery','16');fill('summaryKeep','4');fill('summaryInstruction','整理这两人：测试自定义提示词');click('[data-action="save-summary-settings"]');await wait(()=>$('#mc-notice').textContent.includes('总结设置已保存'),'auto summary config');
 click('[data-tab="chat"]');for(let i=0;i<5;i++){fill('draft','自动总结消息'+i);click('[data-action="send"]');await wait(()=>!$('#mc-status').textContent.includes('正在输入'),'auto summary reply');}
 await wait(()=>readState().threads[0].memory.throughId,'automatic summary stored');const summary=window.mockRequests.find(r=>r.systemPrompt==='整理这两人：测试自定义提示词');assert.ok(summary);assert.ok(summary.prompt[0].content.includes('我的第一条'));assert.ok(!summary.prompt[0].content.includes('城市背景'));assert.equal(readState().threads[1].memory.throughId,'');
 const previousMemory=readState().threads[0].memory;const oldGenerate=window.mockContext.generateRaw;let failSummary=true;
 window.mockContext.generateRaw=async request=>{if(failSummary&&request.systemPrompt.startsWith('整理这两人')){failSummary=false;throw Error('模拟总结失败');}return oldGenerate(request);};
 for(let i=0;i<4;i++){fill('draft','总结失败也要保留回复'+i);click('[data-action="send"]');await wait(()=>!$('#mc-status').textContent.includes('正在输入'),'summary failure reply');}
 assert.equal(failSummary,false);assert.deepEqual(readState().threads[0].memory,previousMemory);assert.ok(readState().threads[0].messages.some(m=>m.text==='总结失败也要保留回复3'));
 fill('draft','再次总结');click('[data-action="send"]');await wait(()=>!$('#mc-status').textContent.includes('正在输入'),'summary retry');assert.notEqual(readState().threads[0].memory.throughId,previousMemory.throughId);
 const saved=readState();assert.equal(saved.profiles.length,2);assert.equal(saved.settings.customInstruction,'自然一点');assert.equal(saved.threads[0].story.frozen,false);assert.equal(saved.settings.storyMemorySource,'worldbook');assert.ok(saved.threads[0].messages.some(m=>m.text.includes('便利店停电了')));
 click('[data-tab="settings"]');assert.equal($('[data-action="create-qr"]'),null);
 window.quickReplyApi.settings.isEnabled=false;window.quickReplyApi.settings.save();globalThis.STMetaCompanion.destroy();await import(pathToFileURL(path.join(base,'index.js')).href+'?reload=1');await wait(()=>$('#mc-wand-button'),'restart');click('#mc-wand-button');click('[data-tab="chat"]');assert.ok($('.mc-messages').textContent.includes('我的第一条'));
 const beforeRestart=extractions();await sleep(400);assert.equal(extractions(),beforeRestart);assert.equal(window.quickReplyApi.settings.isEnabled,false,'restart must honor disabled QR');assert.equal(window.qrCalls.length,3,'restart must not reimport QR or reenable a user-disabled set');
 window.mockContext.chatId='同卡另一个聊天';window.mockEmit('CHAT_CHANGED');await sleep(400);assert.equal(extractions(),beforeRestart);assert.equal($('#mc-profile').options.length,2);
 const originalDescription=window.mockContext.characters[0].description;window.mockContext.characters[0].description+='失败测试';window.failOnce=true;window.mockEmit('WORLDINFO_UPDATED');await wait(()=>$('#mc-notice').textContent.includes('人物自动提取未完成'),'automatic extraction failure');const failedCount=extractions();await sleep(700);assert.equal(extractions(),failedCount,'no automatic retry storm');click('[data-action="close"][aria-label]');click('#mc-wand-button');await wait(()=>extractions()===failedCount+1 && !$('#mc-status').textContent.includes('正在输入'),'reopen retry');assert.equal($('#mc-profile').options.length,2);
 window.mockContext.characters.push({name:'另一张卡',avatar:'another.png',description:'两个测试人物'});window.mockDelay=200;window.mockContext.characterId=1;window.mockEmit('CHAT_CHANGED');await wait(()=>$('#mc-status').textContent.includes('正在输入'),'switched-card extraction');window.mockContext.characterId=0;window.mockEmit('CHAT_CHANGED');await sleep(750);assert.equal($('#mc-profile').options.length,2,'stale extraction must not add contacts');assert.equal(readState().profiles.length,2);window.mockDelay=0;

 const apiCalls=[];globalThis.__TAURITAVERN__={ready:Promise.resolve()};globalThis.fetch=async(url,opts)=>{const body=JSON.parse(opts.body);apiCalls.push({url,body});if(url.endsWith('/status'))return new Response(JSON.stringify({data:[{id:'独立测试模型'}]}));const instruction=body.messages?.[0]?.content || '';const content=instruction.includes('人物设定整理器')?JSON.stringify([{name:'Alpha',personality:'新设定'},{name:'Beta'}]):instruction.startsWith('整理这两人')?'独立 API 摘要':'独立 API 回复';return new Response(JSON.stringify({choices:[{message:{content}}]}));};
 click('[data-tab="settings"]');fill('apiMode','independent');$('[name="apiMode"]').dispatchEvent(new window.Event('change',{bubbles:true}));fill('apiBaseUrl','https://example.test/v1/chat/completions');fill('apiApiKey','test-secret');click('[data-action="api-models"]');await wait(()=>$('#mc-notice').textContent.includes('已读取 1 个模型'),'independent models');assert.equal($('#mc-api-models option').value,'独立测试模型');fill('apiModel','独立测试模型');assert.equal($('[name="apiMaxTokens"]').value,'4096');fill('apiMaxTokens','');fill('apiTemperature','0');click('[data-action="api-test"]');await wait(()=>$('#mc-notice').textContent.includes('连接成功'),'connection test');assert.equal(apiCalls.at(-1).body.temperature,0);assert.ok(!('max_tokens' in apiCalls.at(-1).body));assert.equal(readState().settings.api.mode,'host','testing must not silently save');
 click('[data-action="save-api"]');await wait(()=>$('#mc-notice').textContent.includes('独立 API 配置已保存'),'API save');assert.equal(readState().settings.api.maxTokens,'');const oldHostCalls=window.mockRequests.length;
 click('[data-tab="chat"]');for(let i=0;i<3;i++){fill('draft','独立 API 聊天'+i);click('[data-action="send"]');await wait(()=>!$('#mc-status').textContent.includes('正在输入'),'independent reply');}assert.ok($('.mc-messages').textContent.includes('独立 API 回复'));assert.equal(window.mockRequests.length,oldHostCalls);
 click('[data-tab="settings"]');click('[data-action="summarize"]');await wait(()=>$('#mc-notice').textContent.includes('记忆已更新'),'independent summary');assert.equal(readState().threads[0].memory.text,'独立 API 摘要');
 const profileIds=readState().profiles.map(p=>p.id);window.mockContext.characters[0].description+='独立提取';window.mockEmit('WORLDINFO_UPDATED');await wait(()=>apiCalls.some(c=>c.body.messages?.[0]?.content.includes('人物设定整理器')) && !$('#mc-status').textContent.includes('正在输入'),'independent extraction');assert.deepEqual(readState().profiles.map(p=>p.id),profileIds);assert.equal(window.mockRequests.length,oldHostCalls);
 globalThis.STMetaCompanion.destroy();await import(pathToFileURL(path.join(base,'index.js')).href+'?api-reload=1');await wait(()=>$('#mc-wand-button'),'API restart');click('#mc-wand-button');click('[data-tab="settings"]');assert.equal($('[name="apiMode"]').value,'independent');assert.equal($('[name="apiTemperature"]').value,'0');assert.equal($('[name="apiMaxTokens"]').value,'');assert.equal($('[name="apiApiKey"]').type,'password');
 // Repair a pre-v0.3 import which exists but is hidden, and retry after a failed global activation.
 const stored=readState();stored.qrInstalled=false;localStorage.setItem('meta-companion:state:'+localStorage.getItem('meta-companion:scope'),JSON.stringify(stored));globalThis.STMetaCompanion.destroy();window.quickReplyApi.settings.isEnabled=false;window.quickReplyApi.settings.config.setList[0].isVisible=false;let activationFailed=true;const oldAdd=window.quickReplyApi.addGlobalSet;window.quickReplyApi.addGlobalSet=(...args)=>{if(activationFailed){activationFailed=false;throw Error('模拟 QR 初始化尚未完成');}return oldAdd(...args);};
 await import(pathToFileURL(path.join(base,'index.js')).href+'?qr-repair=1');await wait(()=>readState().qrInstalled===true,'QR activation retry');assert.equal(window.quickReplyApi.settings.isEnabled,true);assert.equal(window.quickReplyApi.settings.config.setList[0].isVisible,true);assert.equal(window.quickReplyApi.getSetByName('映间小手机').length,1,'repair must not create duplicate QR');
 // A new installation must allow independent API setup before the main API is connected.
 globalThis.STMetaCompanion.destroy();window.mockContext.onlineStatus='no_connection';const {freshState}=await import('../core.js');localStorage.setItem('meta-companion:state:'+localStorage.getItem('meta-companion:scope'),JSON.stringify(freshState()));const callsBeforeSetup=window.mockRequests.length;await import(pathToFileURL(path.join(base,'index.js')).href+'?unconnected=1');await wait(()=>$('#mc-wand-button'),'unconnected startup');await sleep(300);assert.equal(window.mockRequests.length,callsBeforeSetup);click('#mc-wand-button');click('[data-tab="settings"]');assert.equal($('[data-action="save-api"]').disabled,false);fill('apiMode','independent');$('[name="apiMode"]').dispatchEvent(new window.Event('change',{bubbles:true}));fill('apiBaseUrl','https://example.test/v1');fill('apiModel','独立测试模型');click('[data-action="save-api"]');await wait(()=>$('#mc-profile').options.length===2 && !$('#mc-status').textContent.includes('正在输入'),'first extraction through independent API');assert.equal(window.mockRequests.length,callsBeforeSetup);
 assert.deepEqual(errors,['模拟网络失败']);console.log('DOM interaction tests passed: independent API config / models / test / chat / extraction / summaries / restart, hidden QR repair and retry, wand, QR, extraction, role isolation, live sync/edit, tag/regex filters, worldbook memory, automatic meta summary, annotations, retry, companionship, restart.');
} finally {globalThis.STMetaCompanion?.destroy();console.error=oldError;await window.happyDOM.close();}
