import { createServer } from 'node:http';
import { readFile,mkdir } from 'node:fs/promises';
import path from 'node:path';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES || '']}));
const base=path.resolve(import.meta.dirname,'..');const artifacts=path.resolve(base,'..','.test-output');await mkdir(artifacts,{recursive:true});
const server=createServer(async(req,res)=>{try{const file=path.resolve(base,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(base+path.sep)){res.writeHead(403).end();return;}const data=await readFile(file);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${server.address().port}/tests/fixture.html`;
const browser=await chromium.launch({headless:true,...(process.env.META_CHROMIUM_PATH?{executablePath:process.env.META_CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']}:{})});
try {
 for(const viewport of [{width:1280,height:800},{width:390,height:844},{width:320,height:650}]) {
    const ctx=await browser.newContext({viewport});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
    const state=()=>page.evaluate(async()=>{const key='meta-companion:state:'+localStorage.getItem('meta-companion:scope');const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('st-meta-companion-native',1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});return new Promise((resolve,reject)=>{const tx=db.transaction('state','readonly');const r=tx.objectStore('state').get(key);r.onsuccess=()=>{resolve(r.result);db.close();};r.onerror=()=>reject(r.error);});});
    const go=async tab=>{await page.locator('.mc-home-button').click();await page.locator(`.mc-app[data-tab="${tab}"]`).click();};
    const idle=()=>page.waitForFunction(()=>!document.getElementById('mc-status').textContent.includes('正在输入'));
    const notice=text=>page.waitForFunction(text=>document.getElementById('mc-notice').textContent.includes(text),text);
    await page.addInitScript(()=>{if(!localStorage.getItem('meta-companion:scope')){localStorage.setItem('meta-companion:scope','legacy-photo-user');localStorage.setItem('meta-companion:state:legacy-photo-user',JSON.stringify({schema:1,profiles:[],threads:[],social:{status:'旧状态'},settings:{}}));}});
    await page.goto(url);if(process.env.META_FONT_FILE){const font=(await readFile(process.env.META_FONT_FILE)).toString('base64');await page.addStyleTag({content:`@font-face{font-family:MetaTestCJK;src:url(data:font/woff2;base64,${font})}#mc-root{font-family:MetaTestCJK,system-ui!important}`});await page.evaluate(()=>document.fonts.ready);}
    await page.locator('#mc-wand-button').click();await page.waitForFunction(()=>document.querySelectorAll('#mc-profile option').length===2);await idle();
    assert.equal((await state()).social.status,'旧状态','legacy localStorage must migrate to IndexedDB');assert.equal(await page.locator('.mc-app').count(),7);assert.match(await page.locator('#mc-home-time').textContent(),/\d{2}:\d{2}/);assert.equal(await page.locator('.mc-nav').count(),0);await page.screenshot({path:path.join(artifacts,`home-${viewport.width}.png`)});
    await go('moments');await page.locator('[data-action="moment-settings"]').click();await page.locator('[name="socialStatus"]').fill('摸鱼');await page.locator('[name^="momentRoles:"]').first().check();await page.locator('[name^="momentCommentRoles:"]').first().check();await page.locator('[data-action="save-moment-settings"]').click();await notice('设置已保存');assert.equal((await state()).social.status,'摸鱼');
    const upload=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=480;c.height=280;const x=c.getContext('2d');const g=x.createLinearGradient(0,0,480,280);g.addColorStop(0,'#a6c3f0');g.addColorStop(1,'#d8c4ed');x.fillStyle=g;x.fillRect(0,0,480,280);return c.toDataURL('image/png').split(',')[1];}),'base64');
    const chooser=page.waitForEvent('filechooser');await page.locator('[data-action="moment-cover"]').first().click();await (await chooser).setFiles({name:'cover.png',mimeType:'image/png',buffer:upload});await page.waitForFunction(()=>Boolean(document.querySelector('.mc-cover-image')));assert.match((await state()).social.cover,/^data:image\/jpeg/);
    await page.locator('[data-action="moment-compose"]').click();await page.locator('[name="momentText"]').fill('今天想慢一点。<script>不可执行</script>');const photos=page.waitForEvent('filechooser');await page.locator('[data-action="moment-photos"]').click();await (await photos).setFiles({name:'photo.png',mimeType:'image/png',buffer:upload});await page.locator('.mc-photo-preview img').waitFor();
    await page.locator('[data-action="moment-publish"]').click();await notice('朋友圈已发表');assert.equal((await state()).social.moments[0].images.length,1);assert.match(await page.locator('.mc-social-text').first().textContent(),/<script>/);assert.equal(await page.locator('#mc-content script').count(),0);
    await page.locator('[data-action="moment-like"]').click();await page.locator('[data-action="social-comment-open"]').click();await page.locator('[name^="comment:"]').fill('自己的评论');await page.locator('[data-action="social-comment"]').click();await page.waitForFunction(()=>document.querySelector('.mc-social-comments')?.textContent.includes('自己的评论'));assert.equal((await state()).social.moments[0].comments.length,1);
    await page.locator('[data-action="social-view-photo"]').click();await page.locator('.mc-photo-dialog img').waitFor();await page.locator('.mc-photo-dialog button').click();
    const callsBefore=await page.evaluate(()=>window.mockRequests.length);await page.locator('[data-action="social-generate"]').click();await page.locator('[data-action="social-generate-confirm"]').click();await notice('等待接入作者提供');assert.equal(await page.evaluate(()=>window.mockRequests.length),callsBefore,'empty prompts must not call an API');await page.locator('[data-action="social-dismiss"]').click();
    await page.screenshot({path:path.join(artifacts,`moments-${viewport.width}.png`)});
    await go('diary');await page.locator('[data-action="diary-settings"]').click();await page.locator('[name^="diaryRoles:"]').first().check();await page.locator('[name^="diaryCommentRoles:"]').first().check();await page.locator('[name="diaryAuto"]').check();await page.locator('[name="diaryMinutes"]').fill('60');await page.locator('[name="diaryDaily"]').fill('1');await page.locator('[data-action="save-diary-settings"]').click();await notice('设置已保存');
    await page.locator('[data-action="diary-tab"][data-value="user"]').click();await page.locator('[data-action="diary-compose"]').click();await page.locator('[name="diaryTitle"]').fill('留给今天');await page.locator('[name="diaryText"]').fill('写一点属于自己的事。');await page.locator('[data-action="diary-publish"]').click();await notice('日记已保存');assert.equal((await state()).social.diaries[0].authorType,'user');
    // Only this test session supplies temporary fixture prompts; release files stay empty.
    await page.evaluate(async()=>{const m=await import('/social.js');for(const key of Object.keys(m.SOCIAL_PROMPTS))m.SOCIAL_PROMPTS[key]='测试专用提示词';});
    await page.locator('[data-action="social-comment-open"]').click();await page.locator('[name="commentRole"]').selectOption({label:'Alpha'});await page.locator('[data-action="social-generate-comment"]').click();await notice('评论已收到');await idle();assert.equal((await state()).social.diaries[0].comments[0].authorType,'character');
    await page.locator('[data-action="diary-tab"][data-value="character"]').click();await page.locator('[data-action="social-generate"]').click();await page.locator('[data-action="social-generate-confirm"]').click();await notice('角色日记已保存');await idle();assert.equal((await state()).social.diaries.filter(x=>x.authorType==='character').length,1);
    await page.locator('[data-action="social-comment-open"]').click();await page.locator('[name^="comment:"]').fill('给角色日记的评论');await page.locator('[data-action="social-comment"]').click();await page.waitForFunction(()=>document.querySelector('.mc-social-comments')?.textContent.includes('给角色日记的评论'));
    const capCalls=await page.evaluate(()=>window.mockRequests.length);await page.locator('[data-action="social-generate"]').click();await page.locator('[data-action="social-generate-confirm"]').click();await notice('今天已达到生成上限');assert.equal(await page.evaluate(()=>window.mockRequests.length),capCalls);await page.locator('[data-action="social-dismiss"]').click();await page.screenshot({path:path.join(artifacts,`diary-${viewport.width}.png`)});
    for(const tab of ['home','moments','diary']){await go(tab==='home'?'moments':tab);if(tab==='home')await page.locator('.mc-home-button').click();assert.equal(await page.locator('.mc-panel').evaluate(el=>el.scrollWidth>el.clientWidth+1),false,tab+' must fit the phone');}
    const saved=await state();await page.reload();await page.locator('#mc-wand-button').click();await idle();assert.equal(await page.locator('.mc-app').count(),7);await go('moments');assert.equal(await page.locator('.mc-post-photos img').count(),1);assert.match(await page.locator('.mc-social-comments').textContent(),/自己的评论/);assert.equal((await state()).social.cover,saved.social.cover);
    await go('diary');assert.match(await page.locator('.mc-social-comments').textContent(),/给角色日记的评论/);await page.locator('[data-action="diary-tab"][data-value="user"]').click();assert.match(await page.locator('.mc-diary-entry').textContent(),/留给今天/);assert.equal((await state()).social.diaries[0].comments[0].authorName,'Alpha');assert.deepEqual((await state()).social.schedules,saved.social.schedules);
    assert.deepEqual(errors,[]);await ctx.close();console.log(`Social UI ${viewport.width}px: home, state / permissions, local cover and photos, escaped content, likes, both comment directions, blank prompt guard, manual generation / daily cap, restart / schedule persistence passed`);
 }
}finally{await browser.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
